
module =
    "module", path, ";",
    { declaration }
;

declaration =
    { attribute },
    (
        include_decl
      | function_decl
      | variable_decl
      | type_decl
      | constraint_decl
    )
;

attribute = 
    "@", identifier,
    [
        "(",
        [
            expression,
            { ",", expression }
        ],
        ")"
    ]
;

include_decl =
    "include",
    path,
    [ "=", identifier ],
    ";"
;

variable_decl =
    type_expr,
    identifier,
    [ "=", expression ],
    ";"
;

type_decl =
    "type",
    identifier,
    [ "=", type_expr ],
    ";"
;

constraint_decl =
    "constraint",
    identifier,
    [ "=", constraint_expr ],
    ";"
;

function_decl =
    [ "$" ],
    "fn",
    type_expr,
    identifier,
    "(",
    [
        parameter_spec,
        { ",", parameter_spec }
    ],
    ")",
    "{",
    { statement },
    "}"
;

parameter_spec =
    type_expr,
    identifier
;

statement =
    (
        expression
      | declaration
      | block_stmt
      | if_stmt
      | for_stmt
      | while_stmt
      | break_stmt
      | continue_stmt
      | match_stmt
      | defer_stmt
    ),
    ";"
;

block_stmt = 
    "{", statement, "}"
;

if_stmt = 
    "if",
    "(", expression, ")",
    statement,
    [
        "else",
        statement
    ]
;

for_stmt = 
    "for",
    "(",
    statement,
    expression, ";",
    expression,
    ")",
    statement
;

while_stmt = 
    "while",
    "(", expression, ")",
    statement
;

break_stmt =
    "break",
    [ expression ]
;

continue_stmt =
    "break",
    [ expression ]
;

match_stmt =
    "match",
    "(", expression, ")",
    "{",
    { match_part },
    "}",
;

match_part =
    type_expr,
    [ identifier ],
    block_stmt,
;

defer_stmt =
    "defer",
    [ expression ]
;
expression = 
        literal
      | initializer
      | parenthesised_expr
      | unary_expr
      | binary_expr
      | conditional_expr
      | call_expr
      | index_expr
      | member_expr
      | cast_expr
      | intrinsic_expr
      | lambda_expr
      | code_expr
      | splice_expr
      (* | type_expr *)
      (* | constraint_expr *)
;

literal = 
        keyword_literal
      | integer_literal
      | float_literal
      | boolean_literal
      | char_literal
      | string_literal
      (* these would go in type_expr *)
      | struct_literal
      | union_literal
      | enum_literal
;

(* to make it easier to change later *)
type_expr = expression;
constraint_expr = expression;

keyword_literal = 
        "null"
      | "true" | "false"
      (* these would go in type_expr *)
      | "none"
      | "bool"
      | integer_type_literal
      | "float16" | "float32" | "float64"
      | "any"
;

integer_type_literal =
      | "int8" | "int16" | "int32" | "int64"
      | "uint8" | "uint16" | "uint32" | "uint64"
;

struct_literal = 
    "struct",
    [ ":", constraint_expr ],
    "{",
    { struct_field },
    "}"
;

struct_field = 
    type_expr,
    identifier
;

union_literal = 
    "union",
    "{",
    { struct_field },
    "}"
;

union_field = 
    type_expr,
    identifier
;

enum_literal = 
    "enum",
    [ ":", integer_type_literal ],
    "{",
    { enum_value },
    "}"
;

enum_value =
    identifier,
    [ "=", expression ]
;

initializer = 
    "{", { init_field }, "}"
;

init_field = 
    [
        ".",
        ( 
            identifier
            |
            "[", expression, "]"
        ),
        "="
    ],
    expression
;

parenthesised_expr =
    "(", expression, ")"
;

unary_expr =
        prefix_unary_expr
      | postfix_unary_expr
;

prefix_unary_expr = 
    prefix_unary_op, expression
;

prefix_unary_op =
        "+" | "-"
      | "++" | "--"
      | "~"
      | "!"
      | "*" | "&"
      | "mut"
;

postfix_unary_expr = 
    expression, postfix_unary_op
;

postfix_unary_op =
        "++"
      | "--"
      | "?"
      | (
            [ "mut" ],
            "*",
        )
      | (
            [ "mut" ],
            "[",
            [ expression ],
            "]"
        )
;

binary_expr =
    expression,
    binary_op,
    expression
;

binary_op = 
        "+" | "-" | "*" | "/" | "%"
      | "&" | "|" | "^" | "~&" | "~|" | "<<" | ">>" | ">>>"
      | "&&" | "||" | "!&" | "!|"
      | "==" | "!=" | "<" | "<=" | ">" | ">="
      | "="
      | "+=" | "-=" | "*=" | "/=" | "%="
      | "&=" | "|=" | "^=" | "~&=" | "~|=" | "<<=" | ">>=" | ">>>="
      | "&&=" | "||=" | "!&=" | "!|="
;

conditional_expr =
    expression,
    "?",
    expression,
    ":",
    expression
;

call_expr = 
    expression,
    "(",
    [
        expression,
        { ",", expression }
    ],
    ")"
;

index_expr = 
    expression,
    "[",
    expression,
    "]"
;

member_expr =
    expression,
    ".",
    identifier
;

cast_expr =
    "(",
    type_expr,
    ")",
    expression,
;

intrinsic_expr =
    "#",
    path,
    "(",
    [
        expression,
        { ",", expression }
    ],
    ")"
;

lambda_expr =
    [ "$" ],
    "fn",
    type_expr,
    identifier,
    "(",
    [
        parameter_spec,
        { ",", parameter_spec }
    ],
    ")",
    "{",
    { statement },
    "}"
;

code_expr = 
    "#",
    "{",
    (* tbd *)
    "}"
;

splice_expr = 
    "#",
    "(",
    expression,
    ")"
;

path =
    identifier,
    { "::", identifier }
;

identifier = ? defined in lexing ?;

null_literal = ? defined in lexing ?;

integer_literal = ? defined in lexing ?;

float_literal = ? defined in lexing ?;

boolean_literal = ? defined in lexing ?;

char_literal = ? defined in lexing ?;

string_literal = ? defined in lexing ?;
